### PR TITLE
R4 37

### PR DESCRIPTION
**Pull request by simon-ess**
Updates the asyn.Makefile to use the DBDCAT-type rules that are included in require 3.2.0.

### CODE REVIEW

**Comment by waynelewis** [comment]
Looks good to me.

**Comment by waynelewis** [comment]
Here is the devEpics.dbd built from vanilla EPICS base 7.0.3.1 and asyn 4-37:

```
# Generated file devEpics.dbd

include "devAsynOctet.dbd"
include "devAsynInt32.dbd"
include "devAsynInt8Array.dbd"
include "devAsynInt16Array.dbd"
include "devAsynInt32Array.dbd"
include "devAsynInt32TimeSeries.dbd"
include "devAsynUInt32Digital.dbd"
include "devAsynFloat64.dbd"
include "devAsynFloat32Array.dbd"
include "devAsynFloat64Array.dbd"
include "devAsynFloat64TimeSeries.dbd"
include "devAsynRecord.dbd"
include "devAsynInt64.dbd"
include "devAsynInt64Array.dbd"
include "devAsynInt64TimeSeries.dbd"
```

**Review by joaopaulosm — APPROVED** [review]
I've just tested locally and works nice, module was loaded without any linking error.

**Comment by waynelewis** [comment]
4-37 is being built now using Gitlab wrapper: https://gitlab.esss.lu.se/e3/common/e3-asyn

**Pull request closed without merging**
